services:

  duckdb:
    build:
      context: ./1_dockerDuckDb
    volumes:
      - ./../data/Flow01:/data/Flow01
    # pour une gestion du flux via Kestra utiliser la ligne suivante
    command: sh -c "tail -f /dev/null"
  
  testexport:
    build:
      context: ./2_dockerTestExport
    volumes:
      - ./../data/Flow01:/data/Flow01
    # pour une gestion du flux via Kestra utiliser la ligne suivante
    command: sh -c "tail -f /dev/null"
  